apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: elk  # You can change the namespace if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: elk  # You can change the namespace if needed
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # The service port
      targetPort: 80    # The container port
      nodePort: 30080   # The external node port (optional; can be in the range 30000-32767)
  type: NodePort
